services:
  - docker
matrix:
  include:
    - language: go
      sudo: false
      go:
      - "1.12"
      env:
        - GO111MODULE=on
      script:
        go test -v ./... -cover

    - language: node_js
      node_js:
      - "10"
      install:
      - npm ci
      script:
      - npm t


deploy:
  provider: heroku
  app: wasm-playground
  api_key: $HEROKU_API_KEY
