services:
  - docker
jobs:
  include:
    - stage: test
    - name: test go
    - language: go
      sudo: false
      go:
      - "1.12"
      env:
        - GO111MODULE=on
      script:
        go test -v ./... -cover
    - name: test node
    - language: node_js
      node_js:
      - "10"
      install:
      - npm ci
      script:
      - npm t
    - stage: deploy
      deploy:
        provider: heroku
        app: wasm-playground
        api_key: $HEROKU_API_KEY
