jobs:
  include:
    - stage: test
      name: Test Go
      language: go
      sudo: false
      go:
      - "1.12"
      env:
        - GO111MODULE=on
      script:
        go test -v ./... -cover
    - name: Test Node
      language: node_js
      node_js:
      - "10"
      install:
      - npm ci
      script:
      - npm t
    - stage: deploy
      name: Deploy to Heroku
      language: minimal
      services:
        - docker
      deploy:
        provider: heroku
        app: wasm-playground
        api_key: $HEROKU_API_KEY

notifications:
  email: false
